### PR TITLE
features: sort tables before generate

### PR DESCRIPTION
**Pull request by ahmadsyamim**

### CODE REVIEW

**Comment by kitloong** [comment]
Hi @ahmadsyamim , thanks for the pull request. Could you please provide the reason of sort the name?

**Comment by ahmadsyamim** [comment]
@kitloong 
Using postgres on different machine, table name list is sorted differently. Causing unsorted table name on migration file which caused tracking changes difficult.

**Comment by kitloong** [comment]
Thank you, please fix the `phpcs` style check.

**Review by ahmadsyamim — COMMENTED** [review]
remove unused param

**Pull request merged**
